# Generated by Django 5.1 on 2025-01-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
